language: rust
rust:
  - stable
script:
  - cargo build --release
  - cargo build --release --features kvm-v4_14_0
  - cargo build --release --features kvm-v4_20_0
  - cargo test
  - cargo test --features kvm-v4_14_0
  - cargo test --features kvm-v4_20_0
